/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.24.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _2 from "./MeshVault.types";
import * as _3 from "./MeshVault.client";
export namespace contracts {
  export const MeshVault = { ..._2,
    ..._3
  };
}