/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.19.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {}
export type ExecuteMsg = {
  delegate: {
    amount: Uint128;
    validator: string;
  };
} | {
  undelegate: {
    amount: Uint128;
    validator: string;
  };
} | {
  withdraw_delegator_reward: {
    validator: string;
  };
} | {
  withdraw_to_costumer: {
    consumer: string;
    validator: string;
  };
} | {
  sudo: StakingSudoMsg;
};
export type Uint128 = string;
export type StakingSudoMsg = {
  add_consumer: {
    consumer_address: string;
    funds_available_for_staking: Coin;
  };
} | {
  remove_consumer: {
    consumer_address: string;
  };
};
export interface Coin {
  amount: Uint128;
  denom: string;
  [k: string]: unknown;
}
export type QueryMsg = {
  all_delegations: {
    consumer: string;
  };
} | {
  consumer: {
    address: string;
  };
} | {
  consumers: {
    limit?: number | null;
    start?: string | null;
  };
} | {
  delegation: {
    consumer: string;
    validator: string;
  };
} | {
  all_validators: {
    consumer: string;
    limit?: number | null;
    start?: string | null;
  };
};
export type ArrayOfDelegation = Delegation[];
export interface Delegation {
  delegation: Uint128;
  validator: string;
}
export type ArrayOfString = string[];
export type Decimal = string;
export interface ConsumerInfo {
  available_funds: Uint128;
  rewards: ConsumerRewards;
  total_staked: Uint128;
}
export interface ConsumerRewards {
  paid_rewards_per_token: Decimal;
  pending: Decimal;
}
export type Addr = string;
export type ArrayOfAddr = Addr[];