/**
 * This file was automatically generated by @cosmwasm/ts-codegen@0.19.0.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run the @cosmwasm/ts-codegen generate command to regenerate this file.
 */

export interface InstantiateMsg {
  denom: string;
}
export type ExecuteMsg =
  | {
      bond: {};
    }
  | {
      unbond: {
        amount: Uint128;
      };
    }
  | {
      grant_claim: {
        amount: Uint128;
        provider: string;
        validator: string;
      };
    }
  | {
      release_claim: {
        amount: Uint128;
        owner: string;
      };
    }
  | {
      slash_claim: {
        amount: Uint128;
        owner: string;
      };
    };
export type Uint128 = string;
export type QueryMsg = {
  balance: {
    account: string;
  };
};
export interface BalanceResponse {
  bonded: Uint128;
  claims: Lein[];
  free: Uint128;
}
export interface Lein {
  amount: Uint128;
  provider: string;
}
