/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.17.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { CosmWasmClient } from "@cosmjs/cosmwasm-stargate";
import { Decimal, InstantiateMsg, ProviderInfo, ExecuteMsg, QueryMsg, Addr, Config } from "./MeshConsumer.types";
export interface MeshConsumerReadOnlyInterface {
  contractAddress: string;
  config: () => Promise<Config>;
}
export class MeshConsumerQueryClient implements MeshConsumerReadOnlyInterface {
  client: CosmWasmClient;
  contractAddress: string;

  constructor(client: CosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.config = this.config.bind(this);
  }

  config = async (): Promise<Config> => {
    return this.client.queryContractSmart(this.contractAddress, {
      config: {}
    });
  };
}