/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.17.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {}
export type ExecuteMsg = {
  delegate: {
    amount: Uint128;
    validator: string;
  };
} | {
  undelegate: {
    amount: Uint128;
    validator: string;
  };
} | {
  withdraw_delegator_reward: {
    validator: string;
  };
} | {
  sudo: SudoMsg;
};
export type Uint128 = string;
export type SudoMsg = {
  add_consumer: {
    consumer_address: string;
    funds_available_for_staking: Coin;
  };
} | {
  remove_consumer: {
    consumer_address: string;
  };
};
export interface Coin {
  amount: Uint128;
  denom: string;
  [k: string]: unknown;
}
export type QueryMsg = {
  all_delegations: {
    consumer: string;
  };
} | {
  consumer: {
    address: string;
  };
} | {
  consumers: {};
} | {
  delegation: {
    consumer: string;
    validator: string;
  };
} | {
  all_validators: {
    consumer: string;
  };
};
export type Addr = string;
export interface AllDelegationsResponse {
  delegations: Delegation[];
  [k: string]: unknown;
}
export interface Delegation {
  amount: Coin;
  delegator: Addr;
  validator: string;
  [k: string]: unknown;
}
export type Decimal = string;
export interface AllValidatorsResponse {
  validators: Validator[];
  [k: string]: unknown;
}
export interface Validator {
  address: string;
  commission: Decimal;
  max_change_rate: Decimal;
  max_commission: Decimal;
  [k: string]: unknown;
}
export interface ConsumerInfo {
  available_funds: Uint128;
  total_staked: Uint128;
}
export interface ConsumersResponse {
  consumers: ConsumerInfo[];
}
export interface DelegationResponse {
  delegation?: FullDelegation | null;
  [k: string]: unknown;
}
export interface FullDelegation {
  accumulated_rewards: Coin[];
  amount: Coin;
  can_redelegate: Coin;
  delegator: Addr;
  validator: string;
  [k: string]: unknown;
}