/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.24.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _6 from "./MeshProvider.types";
import * as _7 from "./MeshProvider.client";
export namespace contracts {
  export const MeshProvider = { ..._6,
    ..._7
  };
}